# DocMind — developer task runner.
# Single source of truth for the commands CI also runs, so "works on my
# machine" and "works in CI" cannot drift.
SHELL := /bin/bash
PY ?= python
PIP ?= $(PY) -m pip
COMPOSE ?= docker compose
IMAGE ?= ghcr.io/karltkiy/docmind
TAG ?= local
COV_FAIL_UNDER ?= 70

.DEFAULT_GOAL := help

.PHONY: help install lint format format-check typecheck test cov check up down logs build migrate revision clean

help: ## Show this help.
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

install: ## Install runtime + dev + demo dependencies (editable).
	$(PIP) install --upgrade pip
	$(PIP) install -e ".[dev,demo]"
	pre-commit install --install-hooks

lint: ## Run Ruff lint.
	ruff check .

format: ## Auto-format with Ruff.
	ruff format .
	ruff check --fix .

format-check: ## Verify formatting without writing (CI mode).
	ruff format --check .

typecheck: ## Static type checking (mypy) over src/.
	mypy src

test: ## Run the test suite.
	pytest

cov: ## Run tests with coverage and enforce the gate.
	pytest --cov=src --cov-report=term-missing --cov-report=xml \
		--cov-fail-under=$(COV_FAIL_UNDER)

check: lint format-check typecheck cov ## Full local quality gate (mirrors CI).

up: ## Start the full local stack.
	$(COMPOSE) up --build -d

down: ## Stop the local stack.
	$(COMPOSE) down

logs: ## Tail local stack logs.
	$(COMPOSE) logs -f

build: ## Build the production image locally.
	docker build -t $(IMAGE):$(TAG) .

migrate: ## Apply database migrations.
	alembic upgrade head

revision: ## Create a new autogenerated migration (m="message").
	alembic revision --autogenerate -m "$(m)"

clean: ## Remove local caches.
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage coverage.xml
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
